
  trigger:
  - main

  pool:
    vmImage: ubuntu-latest

  steps:
  - script: 
  - task: NodeTool@0
    displayName: NodejsInstallation
    inputs:
      versionSource: 'spec'
      versionSpec: '20.x'
  - task: PowerShell@2
    displayName: NpmInstall
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
        
        npm install
  - task: PowerShell@2
    displayName: NpmBuildStep
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
        
        npm run build
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/build/'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/build.zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/build.zip'
      ArtifactName: 'drop1'
      publishLocation: 'Container'
      MaxArtifactSize: 200
      StoreAsTar: true


