
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: 
- task: NodeTool@0
  displayName: NodejsInstallation
  inputs:
    versionSource: 'spec'
    versionSpec: '20.x'
- task: PowerShell@2
  displayName: NpmInstall
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      npm install
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      npm run build
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/https://github.com/Niteshkushwaha9595fbd/ReactTodoUIMonolith/build'
    ArtifactName: 'drop1'
    publishLocation: 'Container'
    MaxArtifactSize: 200
    StoreAsTar: true


